# Generated by Django 4.2.7 on 2023-11-15 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_rename_question_question_question_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="question",
            new_name="question_text",
        ),
    ]
