# Generated by Django 4.2.9 on 2024-02-04 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0003_remove_poll_pub_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="user",
            new_name="voter",
        ),
        migrations.AddField(
            model_name="poll",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
